Add support for hex colors of 8 chars (with alpha value)
honzatmn/expand-to-hex-color pull request #1
Opened 2024-04-18 12:55 UTC by TrueCodes1

2024-04-18 17:24 UTC, honzatmn commented
Thanks @TrueCodes1 for the first contribution! 

Could you also please update tests with this a few HEX8 examples?

2024-04-18 17:24 UTC, honzatmn requested changes
Please add tests too 🙏

2024-04-19 07:50 UTC, TrueCodes1 commented
> Thanks @TrueCodes1 for the first contribution!
> 
> Could you also please update tests with this a few HEX8 examples?

https://github.com/honzatmn/expand-to-hex-color/pull/1/commits/a4a65e24c7f7fa9f9f4f3b418ed96832eb27b971
- extended tests with `expect(expandToHexColor('#ffffff05')).toBe('#FFFFFF05');`
- ordered tests by number of characters so that it can be easily found if you're looking for specific test by no. of characters
- changed logic for HEX4 - `ABCD` -> `AABBCCDD`

2024-04-19 08:16 UTC, honzatmn approved these changes
Great, thank you!

2024-04-19 08:16 UTC, merged